// Spoiler-gated payload: the Obsession ending recap + Nikki's-fate breakdown is served ONLY here,
// fetched by the reveal button on click. So the page HTML (view-source / curl / scrapers / reader-mode)
// never contains the ending — it appears only after an explicit opt-in click.
const RECAP = `<div class="recap-card"><span class="step">Chapter I</span><h4>The One Wish Willow</h4><p>A novelty toy promises a single wish if you snap its branch. Shy, lovesick Bear breaks it — wishing that his co-worker Nikki would love him more than anyone in the world.</p></div>
<div class="recap-card"><span class="step">Chapter II</span><h4>The Wish Curdles</h4><p>The wish doesn't make Nikki happy — it overwrites her. Her devotion curdles into something violent and unrecognizable, while the real Nikki is trapped, screaming inside.</p></div>
<div class="recap-card"><span class="step">Chapter III</span><h4>Two Friends Fall</h4><p>Under the Willow's control, Nikki's hands take the lives of friends Ian and Sarah. Ian, in his final moments, burns his own wish on a billion dollars. The money does not vanish.</p></div>
<div class="recap-card"><span class="step">Chapter IV</span><h4>Bear Breaks The Spell</h4><p>To free her, Bear sacrifices himself — ending both their wishes. It's a devastating, tragic choice the director frames as a Romeo-and-Juliet mirror. As he goes, the curse releases Nikki.</p></div>
<div class="recap-card"><span class="step">Chapter V</span><h4>The Cruelest Frame</h4><p>Nikki wakes — herself again — surrounded by three bodies, sirens closing in. She was never in control. No one will ever believe that. The credits roll on a woman about to be blamed for everything.</p></div>
<div class="recap-card"><span class="step">The Alternate</span><h4>The Ending We Almost Got</h4><p>Barker filmed a darker version where Nikki doesn't survive. On his father's advice, he shot one take where she lives — and the cast realized her surviving was the more devastating choice.</p></div>`;

const FATE = `<div class="fate reveal" style="--accent:#8a5832">
      <svg class="fate-art" viewBox="0 0 120 120" fill="none"><rect x="20" y="22" width="80" height="76" rx="4" stroke="#c08443" stroke-width="2.5"/><path d="M34 22v76M50 22v76M70 22v76M86 22v76" stroke="#c08443" stroke-width="2.5"/><circle cx="60" cy="56" r="9" fill="#271e18" stroke="#d9a25c" stroke-width="2"/><path d="M48 88c2-9 22-9 24 0" stroke="#d9a25c" stroke-width="2"/></svg>
      <div class="fate-body"><h3>1 · She Takes The Fall</h3><span class="verdict">Most Likely · Prison</span><p>Three bodies, one survivor, her DNA on everything. "Possession" isn't a defense any jury will hear. Worse — when police trace Ian's wished-for billion, they'll read it as motive and stack theft on top of the homicides.</p><p class="src">Backed by Barker: it's "more likely the cops find the money and she goes to jail."</p><div class="meter"><div class="meter-top"><span class="lab">Vault odds</span><span class="pct" data-count="58" data-suffix="%">58%</span></div><div class="meter-track" role="meter" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100" aria-label="Vault odds for this ending" aria-valuetext="58% — most likely"><div class="meter-fill" data-pct="58" style="width:58%"></div></div></div></div>
    </div>
    <div class="fate reveal" style="--accent:#5f8593">
      <svg class="fate-art" viewBox="0 0 120 120" fill="none"><circle cx="60" cy="60" r="40" stroke="#5f8593" stroke-width="2.5"/><path d="M60 30c-10 14-10 26 0 30 10-4 10-16 0-30z" stroke="#d9a25c" stroke-width="2"/><circle cx="60" cy="74" r="4" fill="#5f8593"/><path d="M40 92c6-10 34-10 40 0" stroke="#5f8593" stroke-width="2"/></svg>
      <div class="fate-body"><h3>2 · The Asylum Route</h3><span class="verdict">Plausible · Institutionalized</span><p>A defense leans into the only story that fits an impossible scene: she snapped. Not guilty by reason of insanity lands her in a psychiatric facility instead of a cell. Still not freedom — and the entity's "sleep" becomes a clock no doctor can chart.</p><p class="src">Consistent with the film's framing that no one could believe the truth.</p><div class="meter"><div class="meter-top"><span class="lab">Vault odds</span><span class="pct" data-count="18" data-suffix="%">18%</span></div><div class="meter-track" role="meter" aria-valuenow="18" aria-valuemin="0" aria-valuemax="100" aria-label="Vault odds for this ending" aria-valuetext="18%"><div class="meter-fill" data-pct="18" style="width:18%"></div></div></div></div>
    </div>
    <div class="fate reveal" style="--accent:#ab8a5a">
      <svg class="fate-art" viewBox="0 0 120 120" fill="none"><rect x="26" y="44" width="68" height="40" rx="4" stroke="#ab8a5a" stroke-width="2.5"/><circle cx="60" cy="64" r="11" stroke="#ab8a5a" stroke-width="2.5"/><path d="M60 58v12M55 64h10" stroke="#d9a25c" stroke-width="2"/><path d="M40 96l40-72" stroke="#8a5832" stroke-width="2" opacity=".4"/></svg>
      <div class="fate-body"><h3>3 · The Clean Getaway</h3><span class="verdict">Long Shot · She Vanishes</span><p>The optimist's ending: she cleans up, changes clothes, finds Ian's billion before the sirens arrive, and disappears into a new name and a new country. Haunted, rich, free.</p><p class="src">Barker floated this himself — then called it "comforting" but unlikely.</p><div class="meter"><div class="meter-top"><span class="lab">Vault odds</span><span class="pct" data-count="12" data-suffix="%">12%</span></div><div class="meter-track" role="meter" aria-valuenow="12" aria-valuemin="0" aria-valuemax="100" aria-label="Vault odds for this ending" aria-valuetext="12%"><div class="meter-fill" data-pct="12" style="width:12%"></div></div></div></div>
    </div>
    <div class="fate reveal" style="--accent:#c08443">
      <svg class="fate-art" viewBox="0 0 120 120" fill="none"><path d="M60 20C60 20 40 40 40 60a20 20 0 0040 0C80 40 60 20 60 20z" stroke="#c08443" stroke-width="2.5"/><circle cx="52" cy="58" r="3" fill="#d9a25c"/><circle cx="68" cy="58" r="3" fill="#d9a25c"/><path d="M50 70c4 4 16 4 20 0" stroke="#8a5832" stroke-width="2"/></svg>
      <div class="fate-body"><h3>4 · The Wish Isn't Finished</h3><span class="verdict">Wildcard · It Follows</span><p>The grounded crowd will hate this — but the Willow runs on contracts, not hauntings. If Bear's sacrifice only paused the entity rather than ending it, whatever rode Nikki could be dormant, waiting for the next branch to snap.</p><p class="src">Fan reading drawn from the "asleep, not gone" beat before the finale.</p><div class="meter"><div class="meter-top"><span class="lab">Vault odds</span><span class="pct" data-count="8" data-suffix="%">8%</span></div><div class="meter-track" role="meter" aria-valuenow="8" aria-valuemin="0" aria-valuemax="100" aria-label="Vault odds for this ending" aria-valuetext="8%"><div class="meter-fill" data-pct="8" style="width:8%"></div></div></div></div>
    </div>
    <div class="fate reveal" style="--accent:#d9a25c">
      <svg class="fate-art" viewBox="0 0 120 120" fill="none"><path d="M60 24v66" stroke="#d9a25c" stroke-width="2.5"/><path d="M36 40h48" stroke="#d9a25c" stroke-width="2.5"/><path d="M36 40l-10 22h20zM84 40l-10 22h20z" stroke="#d9a25c" stroke-width="2"/><path d="M44 96h32" stroke="#d9a25c" stroke-width="2.5"/><circle cx="60" cy="30" r="3" fill="#c08443"/></svg>
      <div class="fate-body"><h3>5 · Cleared, Eventually</h3><span class="verdict">Outside Bet · Redemption</span><p>A future film digs up the truth — maybe an anthology chapter or sequel that proves the Willow is real. Nikki's name gets cleared years too late: the bleakest possible vindication.</p><p class="src">Hinges on Barker's talk of a sequel or anthology series.</p><div class="meter"><div class="meter-top"><span class="lab">Vault odds</span><span class="pct" data-count="4" data-suffix="%">4%</span></div><div class="meter-track" role="meter" aria-valuenow="4" aria-valuemin="0" aria-valuemax="100" aria-label="Vault odds for this ending" aria-valuetext="4%"><div class="meter-fill" data-pct="4" style="width:4%"></div></div></div></div>
    </div>`;

module.exports = function (req, res) {
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=3600');
  res.setHeader('X-Robots-Tag', 'noindex'); // never index the spoiler payload
  res.end(JSON.stringify({ recap: RECAP, fate: FATE }));
};
